Create The Capricornian Ltd endpoint update
ConsumerDataStandardsAustralia/banking-products-comparator pull request #199
Opened 2022-04-14 06:27 UTC by ShaneCullen155

Update The Capricornian Ltd URL to new endpoint.

Endpoint is changing from;
https://onlinebanking.capricornian.com.au/OpenBanking/

to 

https://public.cdr.onlinebanking.capricornian.com.au

Maintaining the same icon URL, https://www.capricornian.com.au/wp-content/themes/capricornian/images/capricornian-logo.png

Regards,

Shane

2022-04-14 06:50 UTC, vadkor requested changes
Ummm. This PR is trying to merge a patch into nowhere. The patch is also structured incorrectly. You should have forked our repo and made a change in the datasources file. But we see what you tried to do. Do you want to have another go at it or would you like us to make this change for you?

2022-04-14 07:03 UTC, ShaneCullen155 commented
Hello Vadkor,
I'd appreciate it if you could make the change.  I've only added a request once in 2020 to load the original endpoint.  It's a bit unfamiliar.
I tried follow an example at another mutual hosted with Biza.
Thank you,
Shane

2022-04-14 07:09 UTC, vadkor commented
Done.

2022-04-14 07:09 UTC, closed without merging

2022-04-14 07:12 UTC, ShaneCullen155 commented
Thank you, much appreciated.

Regards,

Shane Cullen
Project Officer (IT and Facilities)
The Capricornian
157 East Street, Rockhampton QLD 4700
P: (07) 4931 4915
M: 0439 656 575
E: ***@***.******@***.***>
W: www.capricornian.com.au<http://www.capricornian.com.au/>
***@***.***<https://www.capricornian.com.au/>

The information transmitted in this message and attachments (if any) is intended only for the person or entity to which it is addressed. The message may contain confidential and/or privileged material. Any review, re-transmission, dissemination or other use of, or taking of any action in reliance upon this information, by persons or entities other than the intended recipient is prohibited. If you have received this in error, please contact the sender and delete this email and associated material from any computer. The intended recipient of this email may only use, reproduce, disclose or distribute the information contained in this email and any attached files, with the permission of the sender. The Capricornian Ltd ABN 54 087 650 940 | AFSL / Australian Credit Licence 246780.

From: vadkor ***@***.***>
Sent: Thursday, 14 April 2022 5:10 PM
To: ConsumerDataStandardsAustralia/banking-products-comparator ***@***.***>
Cc: Shane Cullen ***@***.***>; Author ***@***.***>
Subject: Re: [ConsumerDataStandardsAustralia/banking-products-comparator] Create The Capricornian Ltd endpoint update (PR #199)


Closed #199<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fConsumerDataStandardsAustralia%2fbanking%2dproducts%2dcomparator%2fpull%2f199&umid=761957e4-f9fc-40b9-8065-d7ffa30df087&auth=fdbc6ed22f27dc58df2f8c4620d5be98fdcd432b-3e078b0a015c9ed952230126192098c2a46260f4>.

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fConsumerDataStandardsAustralia%2fbanking%2dproducts%2dcomparator%2fpull%2f199%23event%2d6432318488&umid=761957e4-f9fc-40b9-8065-d7ffa30df087&auth=fdbc6ed22f27dc58df2f8c4620d5be98fdcd432b-69ef632835b35c61567640ba8bf58aefad7e236c>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fARMSZOC32X4JCSY4QNON2FTVE7AC3ANCNFSM5TMY3EWQ&umid=761957e4-f9fc-40b9-8065-d7ffa30df087&auth=fdbc6ed22f27dc58df2f8c4620d5be98fdcd432b-13867f08cc9879f9b79d8de0d2bcc3ef20452a95>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-04-19 00:17 UTC, ShaneCullen155 commented
Hi Vadkor,

I've checked the comparator website this morning and it doesn't appear to be retrieving data.

https://consumerdatastandardsaustralia.github.io/banking-products-comparator/

See attached.

It appears to be ok using another site, https://obawv.app/status.htm.

Thanks, 

Shane

![comparator website](https://user-images.githubusercontent.com/72953016/163896334-bcd65fbb-fbeb-4dab-b920-22206aa30ce8.PNG)

2022-04-19 00:36 UTC, vadkor commented
@ShaneCullen155, it must be something on your side. Even your screenshot shows that your datasource URL is as you requested. And it worked just fine for me: 
![image](https://user-images.githubusercontent.com/30234255/163897544-e8ad46ca-e945-4b50-b24a-7947df05ffde.png)
Try cleaning the cache of your browser or opening The Comparator in a Private/Incognito window.

2022-04-19 01:19 UTC, ShaneCullen155 commented
Thanks Vadkor.  The domain is not yet whitelisted in Citrix.  I can access it outside of my Citrix session.
Regards,
Shane