Added Volt Bank API information
ConsumerDataStandardsAustralia/banking-products-comparator pull request #69
Opened 2020-09-30 01:48 UTC by VoltBankThomas

Hi there,

This is a pull request to add the Volt Bank product API to the collection of datasources. 

Thanks

2020-10-01 07:23 UTC, vadkor commented on public/datasources.json
> +
Please remove the empty line.

2020-10-01 07:24 UTC, vadkor requested changes
Your fork is out of date. Please merge in new changes and resolve the conflict.

If you haven't sent one yet, please email us at cdr-data61@csiro.au to verify your association with Volt Bank.

2020-10-01 07:34 UTC, VoltBankThomas commented on public/datasources.json
> +
Done.

2020-10-02 00:51 UTC, vadkor approved these changes

2020-10-02 00:53 UTC, merged